drop table if exists book;
drop table if exists person;

CREATE TABLE person (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        full_name VARCHAR(128) UNIQUE NOT NULL,
        year_of_born INT CHECK (year_of_born > 1900) NOT NULL
);

CREATE TABLE book (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title VARCHAR(128) NOT NULL,
        author VARCHAR(128) NOT NULL,
        year_of_release INT CHECK (year_of_release > 1300) NOT NULL,
        person_id INT REFERENCES person(id) ON DELETE SET NULL
);

INSERT INTO person(full_name, year_of_born)
VALUES ('Коровяков Дмитрий Алексеевич', 1991),
       ('Коровякова Анастасия Андреевна', 1993),
       ('Иванов Иван Иванович', 1949),
       ('Павлова Ольга Владимировна', 1984),
       ('Семенов Алексей Андреевич', 2007),
       ('Бус Буся Бусяновна', 2023);


INSERT INTO book (title, author, year_of_release, person_id)
VALUES ('Философия Java', 'Брюс Эккель', 1998, 2),
       ('Война и мир', 'Лев Толстой', 1867, 1),
       ('1984', 'Джордж Оруэлл', 1949, 2),
       ('Скотный двор', 'Джордж Оруэлл', 1945, 4),
       ('Лолита', 'Владимир Набоков', 1955, 5),
       ('Мальчик в полосатой пижаме', 'Джон Бойн', 2006, 4),
       ('Портрет Дориана Грея', 'Оскар Уайльд', 1890, 1),
       ('Вий', 'Николай Гоголь', 1835, 5),
       ('Гордость и предубеждение', 'Джейн Остен', 1813, null),
       ('Божественная комедия', 'Данте Алигьери', 1314, null);